features/eidas_user_journeys.feature
features/step_definitions/user_steps.rb

Author: @cobainc0
Amended to prefix "IDP" to idp name

BAU: Clean up undefined steps warnings in tests

---

.rubocop.yml
Dockerfile
features/account_creation.feature
features/eidas_user_journeys.feature
features/journey_picker.feature
features/step_definitions/user_steps.rb
features/support/env.rb

- Run cucumber in strict mode so it fails on undefined steps
- Add rubocop config file
- Make the javascript driver the default one
- Minor reformatting to make Ruby styles consistent

BAU: Minor refactoring and general improvements

---

features/eidas_user_journeys.feature
features/journey_hint.feature
features/journey_picker.feature
features/step_definitions/environments.yml
run-tests-with-docker.sh

- Add staging configuration
- Add tags to eIDAS tests
- Modify shell script to support providing --tags

Make changes necessary for running against staging

---

features/account_creation.feature
features/loa1.feature
features/non_repudiation.feature
features/simple.feature

- These steps were in the ida-hub-acceptance-tests, but not replicated here so adding these in.

EID-824 - Add extra steps on acceptance tests

---

features/step_definitions/environments.yml

-Remove references to stub-idp-demo that is no longer being used.
-Add stub-idp-demo-one and stub-idp-demo-two for docker-local environment

EID-895 Tidy up stub IDP's that are not being used.

---

features/authn_failure.feature
features/step_definitions/user_steps.rb

Update authn_failure feature test to reflect new page structure.

HUB-267: Add Single IDP Failure Page

---

features/single_idp_journey.feature
features/step_definitions/environments.yml
features/step_definitions/user_steps.rb

Needs to be merged after [this PR](https://github.com/alphagov/verify-stub-idp/pull/59) is released.

HUB-296: Add acceptance test for Single IDP journey

---

features/journey_hint.feature

Change Journey Hint Acceptance Tests to reflect (temporary) change in journey hint routing

HUB-377: Cookie Based Journey Hinting

---

features/single_idp_journey.feature
features/step_definitions/user_steps.rb

This reverts commit b2c511ff2967f220c22c3f8c88badfce06ab8312, reversing
changes made to 5006ff1ab19a44eb34d1952c3c83244a3bb60c20.
This will hopefully fix joint.

Revert "Merge pull request #63 from alphagov/eid-1463-acceptance-test"

---

features/step_definitions/environments.yml

This change updates the Test RP's URL so that acceptance tests do not fail.
Author: @adityapahuja
Closes #66

AUTO-112: Update to use new Test RP in staging environment

---

features/step_definitions/environments.yml

This pull request updates environments.yml to use new Stub IDP in staging environment. 
Author: @adityapahuja

AUTO-112: Update to use new Stub IDP in staging env

---

features/eidas_connector_node_country_journeys/prod/pt-request.feature

Smoke test from UK Connector Node to PT Proxy Node

🇵🇹EID-1971 Portugal Connector Node smoke test

---

features/step_definitions/user_steps.rb

Alter a step so content matches that of the failure journey.

HUB-247 Adapt to altered content

---

features/eidas_connector_node_country_journeys/integration/pt-request.feature
features/step_definitions/environments.yml

Also add integration environment config to the tests

EID-1927: Add Connector Node integration smoke test for Portugal

---

features/eidas_journeys_account_creation.feature
features/smoke/eidas_connector_node/integration/belgium.feature
features/smoke/eidas_connector_node/integration/estonia.feature
features/smoke/eidas_connector_node/integration/italy.feature
features/smoke/eidas_connector_node/integration/luxembourg.feature
features/smoke/eidas_connector_node/integration/spain.feature
features/smoke/eidas_connector_node/production/estonia.feature
features/smoke/eidas_connector_node/production/luxembourg.feature
features/step_definitions/user_steps.rb

- Fix Luxembourg production smoke test
- Add integration smoke tests for countries currently connected in production

Fix and add Connector Node smoke tests

---

features/smoke/eidas_connector_node/production/estonia.feature

Update our connector node smoke test for Estonia in Prod as the text on their Id Scheme page has changed

🇪🇪💨  BAU Estonia Prod Id Scheme text change

---

features/smoke/eidas_connector_node/integration/estonia.feature
features/smoke/eidas_connector_node/production/estonia.feature

Reverts alphagov/verify-acceptance-tests#100
It didn't work.  I read the problem wrong.  Back it out.  Nothing to see here.

Revert "BAU - Fix Estonia smoketest"

---

features/backward_compatibility.feature

We need to investigate this failure afterwards

BAU Remove backcompat-3 from acceptance tests in order to get a release out and close a P2

---

features/authn_failure.feature
features/back_button.feature
features/backward_compatibility.feature
features/cancel_refuse.feature
features/journey_hint.feature
features/loa2_loa1.feature
features/simple_sign_in.feature
features/step_definitions/user_steps.rb

Reverts alphagov/verify-acceptance-tests#135

Revert "re-enable tests"

---

features/authn_failure.feature
features/back_button.feature
features/backward_compatibility.feature
features/cancel_refuse.feature
features/journey_hint.feature
features/loa2_loa1.feature
features/simple_sign_in.feature
features/step_definitions/user_steps.rb

Reverting the most recent PR in order to restore acceptance tests. https://govukverify.atlassian.net/jira/software/c/projects/HUB/boards/144?modal=detail&selectedIssue=HUB-1240

Revert "Revert "re-enable tests""
