- .gitignore
- .rubocop.yml
- Dockerfile
- features/account_creation.feature
- features/eidas_user_journeys.feature
- features/journey_picker.feature
- features/step_definitions/user_steps.rb
- features/support/env.rb
- Run cucumber in strict mode so it fails on undefined steps
- Add rubocop config file
- Make the javascript driver the default one
- Add no_javascript driver to Selenium
- Minor reformatting to make Ruby styles consistent
- Redefine some steps to support no JavaScript tests
- Print test report to /testreport
> EID-745: Add acceptance tests without JavaScript and print test report

- Dockerfile
- docker-compose.yml
- run-tests-with-docker.sh
- docker ps has an -a flag that allows us to find stopped containers
- we can docker cp out of the container even if it is stopped
- this means that the files are written by whatever calls docker cp
(in this case mostly jenkins)
> BAU: Use docker cp with docker ps -a to get testreports

- features/eidas_user_journeys.feature
- features/support/env.rb
We're doing no JS tests in verify-frontend so we don't need to repeat them here
Also, Selenium remote doesn't support no JS drivers
> EID-745: Remove no JavaScript driver

- features/eidas_user_journeys.feature
- features/step_definitions/user_steps.rb
-The test in question has been breaking intermittently. We are adding an extra check to ensure that the page has succesfully loaded before continuing onto the next step. This should hopefully prevent cucumber checking the wrong page and failing the test.
> BAU: Add assertion to pages on eidas go back test

- docker-compose.yml
- verify-local-startup needs to be able to start these tests
inside its network
- docker-compose >= 3.4 allows the providing of a .overrides.yml
file to add extra sections to docker-compose.yml
- To allow this to work, we need to bump the version in the local
docker-compose
> BAU: Bump docker compose version to allow injection of network

- features/account_creation.feature
- features/authn_failure.feature
- features/back_button.feature
- features/cancel_refuse.feature
- features/feedback.feature
- features/journey_hint.feature
- features/journey_picker.feature
- features/loa1.feature
- features/non_repudiation.feature
- features/simple.feature
- features/step_definitions/environments.yml
- features/step_definitions/user_steps.rb
Created the following new feature files:
feedback.feature
non_repudiation.feature
simple.feature
Made changes to existing tests to account for some code refactoring:
account_creation.feature
loa1.feature
Refactored step_definitions and added the following new steps:
Given('they start a sign in journey but their session times out') do
Given('they login as the newly registered user') do
Given('they do not have their documents') do
Given('they do not have other identity documents') do
Then ('they are shown the cookies missing page') do
When('they go to the feedback form') do
And('they enter some feedback and submit the form') do
Then('they receive confirmation that feedback was sent') do
And('they go back to the start page') do
When('they click {string}') do |value|
NOTE:
Includes commits by …
>  Port over remaining tests from ida-hub-acceptance-tests

- features/step_definitions/environments.yml
The staging config got remove when this PR was merge: 
https://github.com/alphagov/verify-acceptance-tests/pull/17 
This is to put back the change.
> Put back staging config that got removed in a PR that got merged recently

- features/step_definitions/user_steps.rb
There have been changes to text on error page (as part of eidas) and
changes to hint on start page (as part of frontend). This is to update the text
and make the test reset verify session before each test.
> BAU: Fix tests after recent changes

- features/step_definitions/user_steps.rb
- Remove the unneccesary check to match the first IDP as it doesn't offer
any value and seems to cause a lot of problems when introducing stub-idp-demo-one
- When we introduce stub-idp-demo-one, the test fails as it matches this first
instead of what it is meant to be looking for being stub-idp-demo. Removing this
check allow it to match against stub-idp-demo which is the correct behaviour
> Bau - Remove the match first check

- features/account_creation.feature
- features/authn_failure.feature
- features/back_button.feature
- features/cancel_refuse.feature
- features/journey_hint.feature
- features/loa1.feature
- features/non_repudiation.feature
- features/simple.feature
- features/step_definitions/environments.yml
Add the following environment appropriate lines to environments.yml for local, staging and joint.
Stub Idp Demo One: http://localhost:50140/stub-idp-demo-one/login
Stub Idp Demo Two: http://localhost:50140/stub-idp-demo-two/login
Stub Idp Demo One: https://ida-stub-idp-staging.cloudapps.digital/stub-idp-demo-one/login
Stub Idp Demo Two: https://ida-stub-idp-staging.cloudapps.digital/stub-idp-demo-two/login
Stub Idp Demo One: http://localhost:50140/stub-idp-demo-one/login
Stub Idp Demo Two: http://localhost:50140/stub-idp-demo-two/login
Removed entries referencing post-office-stub from environments.yml
Removed references to live IDP's from existing tests and replaced them with Stub Idp Demo One or Stub Idp Demo Two.
> EID-815 Sanitise existing tests by replacing references to live IDP's

- features/eidas_user_journeys.feature
- features/step_definitions/user_steps.rb
- Changes to the MSA means that it can support extra signing algorithms to comply with the eidas spec. 
- Stub country will have the ability to sign assertions with 1 of 2 algorithms, rsassa-pss or rsasha256. By default it signs using the rsasha256 but this added test will allow to sign the stub country response with rsassa-pss without changing the UI to ensure the latest MSA can support this. 
- This is carried out by changing a hidden value within eidasConsent.ftl within verify-stub-idp
> EID-894 - Add acceptance test to check MSA can handle new signing algorithm

- features/account_creation.feature
- features/authn_failure.feature
- features/journey_hint.feature
- features/journey_picker.feature
- features/non_repudiation.feature
- features/step_definitions/user_steps.rb
Added tests to check that the error pages on UAC failure redirect the users to either the service start page (for Verify journeys) or to the Verify/eIDAS picker (for eIDAS journeys).
Added/modified scenarios:
- When user fails IDP signin (AuthnFailure) and clicks through link on error page, they get redirected to Verify Start page (existing behaviour)
- When user fails Country signin (AuthnFailure) and clicks through link on error page, they get redirected to Verify vs eIDAS picker
- When they click Verify they get taken to verify start page
- When they click eIDAS they get taken to country picker
- When user fails IDP UAC and clicks through link on error page, they get redirected to RP service error page (existing behaviour)
- When user fails Country UAC and clicks through link on error …
> EID-795: Add tests to check the Refined error pages work correctly

- features/authn_failure.feature
- features/step_definitions/user_steps.rb
Extended the AuthFailure tests to make sure the user can successfully sign-in with either a country or a Verify IDP after an AuthnFailure response from a country.
Modified scenarios:
- When user fails Country signin (AuthnFailure) and clicks through link on error page, they get redirected to Verify vs eIDAS picker
- When they click Verify they get taken to verify start page and successfully log in
- When they click eIDAS they get taken to country picker and successfully log in
> EID-951: Add tests to check the new error handling flow for eIDAS works correctly

- features/account_creation.feature
Add tests for both sign in and registration for a text rp using
shibboleth which should not be signed by hub.
solo: @rachelthecodesmith
> HUB-280: Add tests for no cycle three, unsigned by hub

- features/step_definitions/user_steps.rb
Renaming test-rp name "register for an identity" profile to "test GOV.UK Verify user journeys" to make the content more readable.
> FIREBREAK: Rename test-rp

- features/single_idp_journey.feature
- features/step_definitions/environments.yml
- features/step_definitions/user_steps.rb
Add acceptance test for the single idp feature to ensure a journey can
be made from the appropriate pages so long as the feature flag is
enabled.
@rachelthecodesmith
> HUB-296: Add acceptance test for single idp feature

- features/simple.feature
- features/step_definitions/user_steps.rb
This PR adds a new acceptance tests to ensure that users cannot register with an IDP no longer providing new user registrations.
Solo: @karlbaker02
> CVQ2-227: Add new acceptance test for disconnected IDPs

- features/simple.feature
- features/step_definitions/user_steps.rb
This PR tests that the hard-disconnection (sign-in) does not display an IDP no longer providing authentication.
Solo: @karlbaker02
> CVQ2-227: Add test for hard-disconnection

- features/back_button.feature
- features/step_definitions/user_steps.rb
This checks that when users select a country they can go back to the journey picker page and successfully log in with a Verify IDP
Added scenario:
- User starts an eIDAS journey, selects a country, then goes back to journey picker page, signs in with an IDP and succeeds
Note: this can only be merged after alphagov/verify-hub#155 and alphagov/verify-frontend#589
> EID-1004: Test transitions from eIDAS to Verify journeys

- features/back_button.feature
This checks that when users select an IDP they can go back to the journey picker page and successfully log in with a country
Added scenario:
- User starts a Verify IDP journey, selects an IDP, then goes back to journey picker page, signs in with a country and succeeds
Note: this can only be merged after alphagov/verify-hub#155, alphagov/verify-hub#158 and alphagov/verify-frontend#589
> EID-1004: Test transitions from Verify to eIDAS journeys

- features/account_creation.feature
- features/eidas_user_journeys.feature
- features/non_repudiation.feature
- features/step_definitions/user_steps.rb
EID-1116 Tidy up verify-acceptance-test step definition
- Consolidate the following step definitions into one:
Given('they login as {string}') do |username|
Given('they login as the newly registered user')
Above two replaced with:
Given(/^they login as "(.*)"( with a random pid)?$/) do |user_string, with_random_pid|
- Create a login function to replace repeated chunk of code that execute user login
def log_in_as(username)
fill_in('username', with: username)
fill_in('password', with: 'bar')
click_on('SignIn')
assert_text("You've successfully authenticated")
end
> EID-1116 Tidy up verify-acceptance-test step definition

- run-tests-with-docker-parallel.sh
We might benefit a bit more from a greater parallelization. This will enable us
to run and test the optimal number of nodes.
Corresponding JJB change https://github.com/alphagov/verify-jenkins-job-builder/pull/312
> BAU: Make number of nodes configurable

- features/eidas_journeys.feature
- features/step_definitions/user_steps.rb
- pre-commit.sh
Added scenarios:
Scenario: English journey - User selects eIDAS scheme that is unavailable and receives correct error page
Scenario: Welsh journey - User selects eIDAS scheme that is unavailable and receives correct error page
Added step definitions:
Given /a user starts the "(.*)" version of the eIDAS journey$/ do |language_version|
Then('they are presented with the correct eIDAS scheme unavailable error page') do
Modified step definition:
Given('they select eIDAS scheme {string}') do |scheme|
> EID-1060 Acceptance tests for eIDAS scheme unavailable error message

- .gitignore
.gems folder is created after running hub acceptance test. It prevents update_project_repos script in verify-build-scripts repo from updating verify-acceptance-tests.
Author: @adityapahuja
> BAU: Ignore .gems folder

- features/step_definitions/user_steps.rb
After the recent capybara gem update the choose command stopped working
as the allow_label_click flag is required
> BAU: Update choose command

- docker-compose.yml
The recent capybara and geckodriver updates allow us to run the tests with the
latest Firefox version. No need to peg the version (yay).
> BAU: Run tests on the latest Firefox

- features/support/env.rb
What
----
We have a selenium hub running at selenium.tools.signin.service.gov.uk
We would like to use it for parallel acceptance tests without the use of
docker compose
When passing the `SELENIUM_HUB_URL` environment variable this will use a
remote selenium hub
How to review
----
```
$ git fetch
$ git checkout -b enable-use-of-tools-selenium origin/enable-use-of-tools-selenium
$ bundle install
$ SELENIUM_HUB_URL="https://selenium.tools.signin.service.gov.uk" \
TEST_ENV=joint \
bundle exec parallel_cucumber -n 2 features
```
> Enable use of selenium.tools.signin.service.gov.uk

- features/simple_sign_in.feature
- features/step_definitions/environments.yml
- features/step_definitions/user_steps.rb
See https://trello.com/c/HKYawdAT/133-add-integration-test-for-disconnected-idp-hints
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
> HKYawdAT: Add integration test for disconnected IDP hints

- features/step_definitions/user_steps.rb
Updated frontend requires an extra link to be clicked to get to the feedback form - add that action to the step.
> Update 'they go to the feedback form' step

- features/eidas_journeys.feature
- features/eidas_journeys_account_creation.feature
- features/step_definitions/user_steps.rb
Adds new tests for:
- regular journeys where the stub country provides unsigned assertions
- account creation journeys where the stub country provides unsigned assertions
**Merge EID-1604 before this PR.**
> EID-1611 tests for unsigned assertion journeys

- features/backward_compatibility.feature
- features/step_definitions/user_steps.rb
This adds tests for MSA backward compatibility.  They reproduce the
old ida-hub-acceptance-tests/msa-backward-compatibility-test.sh which
ran
MsaBackwardsCompatibilityTest.userSignInSuccessfullyAndCompletesNINOCycle3Page.
Basically it's a simple login flow with cycle 3.
The purpose of these tests is that they are run against a separate
test-rp/msa instance, which are running an old but supported version
of the MSA.  These MSAs are already deployed to PaaS and have
pipelines to deploy them.
It's not ideal to hardcode the MSA URL in the feature but I couldn't
think of a better way to achieve this.  I'm open to suggestions.
I have run these locally and they pass :+1: so we are still backwards
compatible, hooray!
> Add MSA backward compatibility tests

- features/eidas/be-request.feature
- features/eidas/es-request.feature
- features/eidas/et-request.feature
- features/eidas/it-request.feature
- features/eidas/lu-request.feature
- features/step_definitions/user_steps.rb
Added a smoke test to the existing infrastructure for all countries connected to the Connector Node in prod
These countries are currently: Estonia, Italy, Luxembourg, Spain, Belgium
(Germany uses middleware so is excluded)
The tests all start from the 'Personal tax account' service. From here sign in with a digital identity from another European country is selected. Then the country of choice is selected and then we check that we have reached the countries hub by asserting we can see specialised text on the page.
Add a smoke test for each country to the Verify Hub Smoke pipeline: https://github.com/alphagov/verify-terraform/pull/1162
> EID-1917: Add smoke tests to all countries connected to Connector Node

- features/eidas_countries_integration/be-request.feature
- features/eidas_countries_integration/es-request.feature
- features/eidas_countries_integration/et-request.feature
- features/eidas_countries_integration/it-request.feature
- features/eidas_countries_integration/lu-request.feature
This is so we can exclude these tests from the Hub deploy pipeline
> BAU: Add tags to eIDAS tests for integration with real countries

- features/eidas_connector_node_country_journeys/prod/be-request.feature
- features/eidas_connector_node_country_journeys/prod/es-request.feature
- features/eidas_connector_node_country_journeys/prod/et-request.feature
- features/eidas_connector_node_country_journeys/prod/it-request.feature
- features/eidas_connector_node_country_journeys/prod/lu-request.feature
- features/step_definitions/user_steps.rb
Check the country page has no error message. This isn't perfect but so far we've seen that if something goes wrong the word "error" or "problem" is included in the page. The regex `i` flag makes the search case-insensitive.
Ideally we'd also check the status code is 200 but the Selenium webdriver doesn't support status codes and this feature won't be introduced into the API by the developer
Refactor user steps to reduce the number of methods by using tokens
> BAU: Make Connector Node smoke tests more robust

- features/eidas_connector_node_country_journeys/prod/it-request.feature
It was asserting on the wrong text duplicated from another test
> BAU: Fix Italy connector node test

- features/step_definitions/user_steps.rb
- pre-commit.sh
New journey was introduced in alphagov/verify-frontend#818
Also allow to specify the environment as an env var when running pre-commit
> HUB-553: Reflect changes to the registration journey in the tests

- features/authn_failure.feature
- pre-commit.sh
Due to changes in alphagov/verify-frontend#821
This is because due to traffic splitting the user will only ever see one IDP.
This is a temporary measure until we fix the splitting logic to be more clever.
Also ignore tests marked with `@ignore` when running locally
> BAU: Remove prompt to try with another IDP on registration failure

- features/loa2_loa1.feature
- Create a new Test RP which has LOA2 first in config followed by LOA1. This will change the order in which the LOAs appear in the AuthnRequest so that LOA2 is first in the list. This is to show that the RP prefers LOA2 but will accept LOA1 if a user fails to get LOA2.
- This RP will go through the LOA1 hub flow.
- Add new feature to test that users on this RP can successfully sign in and register with both LOA1 and LOA2.
> Add new feature test for loa2-loa1 RP

- features/loa2_loa1.feature
- features/step_definitions/user_steps.rb
- When a RP has LOA2,LOA1 in their config we want for that service to still be able to use eIDAS.
- Add eIDAS tests so we can ensure that service can see the eIDAS pages and the prove identity screen.
> Add eIDAS tests for a loa2-loa1 RP

- features/step_definitions/user_steps.rb
See https://govukverify.atlassian.net/browse/HUB-662
**What**
When Covid-19 caused huge peaks in traffic for UC, we added stuff to the hub to:
manage expectations about the IDP delays
explain that users would need to go back to the service after the IDP
These changes appear in the registration users journey after the user selects an IDP on the IDP picker page.
**Why**
- Because we are now reverting see: https://github.com/alphagov/verify-frontend/pull/864
- Above affects **acceptance test** as the warning page will be removed
> Hub 662 remove content and pages about weird journeys

- features/smoke/eidas_connector_node/integration/portugal.feature
- features/smoke/eidas_connector_node/production/belgium.feature
- features/smoke/eidas_connector_node/production/estonia.feature
- features/smoke/eidas_connector_node/production/italy.feature
- features/smoke/eidas_connector_node/production/luxembourg.feature
- features/smoke/eidas_connector_node/production/portugal.feature
- features/smoke/eidas_connector_node/production/spain.feature
To make them consistent with Proxy Node tests and enable country status reporting the Proxy Node from alphagov/verify-terraform#1231
- Move to a common file structure
- Rename to use country names
> Organise eIDAS Connector Node smoke tests

- Dockerfile
The verify-acceptance-tests docker image is quite large right now.
This means that concourse does a lot of work copying it around.
This does three things to reduce the image size:
- use the `ruby:2.6.5-slim` image as base, which is smaller
- add the `--no-install-recommends` option to `apt-get install` to
avoid installing extra dependencies we don't need
- use multi-stage docker builds so that we don't include build
dependencies (like gcc) in the final artefact
This reduces the size from ~900Mb to ~190Mb.
I tried to test this locally, but ./run-tests-with-docker.sh is broken
for me on master: every test fails with:
```
other os error
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '8eccfd00f531', ip: '172.24.0.5', os.name: 'Linux', …
```
> Reduce the size of the built docker image

- features/backward_compatibility.feature
See these PR's on the MSA https://github.com/alphagov/verify-matching-service-adapter/pull/166 and infrastructure config https://github.com/alphagov/verify-infrastructure-config/pull/382 to add the config and infrastructure to allow these tests to run.
> HUB-697: Add MSA 5.0.2 to backwards compatibility tests

- scripts/print-report.sh
Move script from `verify-infrastructure/.../smoketest.yml` to its own file in this repo.
Make script take a parameter that determines which environment it's working on and do a basic check to make sure the parameter is present.
At some point this script might be replaced with some ruby or something that makes it more re-usable.
> EID-2006 Add script to send a report of smoketest output to slack

- features/smoke/eidas_connector_node/integration/estonia.feature
- features/smoke/eidas_connector_node/production/estonia.feature
Removes smoke test steps that click through the CEF reference implementation for Estonia. Apparently Estonia doesn't show these pages to users, or require them to click anything. There's a quick redirect and that's all.
> Remove CEF reference steps for Estonia

- features/step_definitions/user_steps.rb
The Belgians have added a new banner to their landing page (see below) which
includes the work "problems". This matches with our error checking step
which has a regex for "problem".
This commit adds a word boundary to the regex so we don't match the
plural. This is a bit fragile, but it at least preserves some of the
functionality.
> BAU: Fix Belgian connector-node smoke tests

- features/smoke/eidas_connector_node/integration/estonia.feature
- features/smoke/eidas_connector_node/production/estonia.feature
- features/step_definitions/user_steps.rb
It's a link, not a button, to change the language to English.
This fixes prod but integration is broken from some sort of SAML'y
reason.
> BAU: Fix Estonia connector node test

- features/eidas_journeys_account_creation.feature
- features/pause_and_resume.feature
The string that matches the placeholder needs to be quoted, otherwise it
assumes there is a step with that literal name.
> BAU: Correctly use refactored step

- Dockerfile
- features/support/env.rb
- run-tests-with-docker.sh
You can see these changes running in Concourse here: https://cd.gds-reliability.engineering/teams/verify/pipelines/deploy-verify-hub/jobs/test-hub-staging-tinkering/builds/9
We've found recently that the Selenium grid running in ECS has been very
unreliable and has prevented releases from progressing though the hub
pipeline. Acceptance tests would often timeout, amongst other errors.
The grid shows high use of memory and CPU which could be a contributing
factor. Attempts to diagnose the reason for this flakiness have been
fruitless.
This commit switches to using a local firefox driver. This seems to work
reliably, and means if we can stop using the grid we have one less thing
to maintain/worry about.
The logic is slightly re-ordered in the `env.rb` file so that the case
when we're running …
> BAU: Remove use of Selenium grid

- features/backward_compatibility.feature
They're blocking the pipeline and are redundant at the moment due to all
MSAs being upgraded recently
> BAU: Ignore backwards compatibility tests

- features/backward_compatibility.feature
All services were recently asked to upgrade their MSA. All MSAs in the
wild are now running version 5.0.2-5.0.2 except for two.
One of the other two is still on 4.2.1-901 but have updated their trust
stores to be useable with the new G3 PKI. The other service appears to
be using version 4.1.0 but is not responding to communications to
upgrade.
We have changed the signing certificates used by stub-idp in staging and
integration to the certs from the dev-pki PKI. The trust stores included
with versions of the MSA before 5.0.2 do not include the dev-pki PKI CA
certs and as such will no longer work in integration. Because of this we
should no longer support them.
Version 4.2.1 is being left here as we know we have one service using it
with upgraded trust stores.
We will soon be rolling out …
> HUB-812: Remove redundant back compat tests

- features/step_definitions/user_steps.rb
The heading on failed registration page has change due to
accessibility requirements see https://govukverify.atlassian.net/browse/HUB-242
https://github.com/alphagov/verify-frontend/pull/939
> HUB-242: update due to change to heading

- features/backward_compatibility.feature
And restore tests for MSA 4.2. This was failing previously, and we removed it to get out a release.
> EID-2031 add acceptance tests for  Test RP using MSA 5.1.0

- docker-compose.yml
- run-tests-with-docker.sh
We [vendored](https://github.com/alphagov/verify-terraform/pull/1429) selenium hub and node-firefox.
Mitigate [docker hub rate limits](https://cd.gds-reliability.engineering/teams/verify/pipelines/deploy-stubs/jobs/staging-acceptance-tests/builds/81) by using these vendored ghcr.io images.
Tested locally with `./run-tests-with-docker.sh`.
> BAU Use vendored selenium hub and firefox

- Dockerfile
- docker-compose.yml
In order to use dockerhub rather than GHCR we need to pass in the base_image ARG so that we can use it later on in the build.
> [HUB-841] Use Docker Hub rather than GHCR

- features/authn_failure.feature
`test-rp-with-continue-on-fail` is only available in local env.
Anyway we should remove the "continue on fail" feature as it's not used in prod
> HUB-971: Remove failing tests
